# Prepare Reference Projections
Manually process those

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import socket as socket
import os as os
import sys as sys
import multiprocessing as mp

socket_name = socket.gethostname()
    
if socket_name.startswith("bionc") or socket_name.startswith("hpc"):
    print("Leipzig Cluster detected!")
    path = "/mnt/archgen/users/hringbauer/git/projectPCA/"   
    #path = "/mnt/archgen/users/hringbauer/"
else: 
    raise RuntimeWarning("Not compatible machine. Check!!")
     
os.chdir(path)  # Set the right Path (in line with Atom default)
print(os.getcwd())
print(f"CPU Count: {mp.cpu_count()}")
print(sys.version_info)

#from projectPCA.eigenstrat_funcs import load_genos_autoeager, update_values
from projectPCA.run import project_eigenstrat

%config InlineBackend.print_figure_kwargs={'facecolor' : "w"}

Leipzig Cluster detected!
/mnt/archgen/users/hringbauer/git/projectPCA
CPU Count: 128
sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)

# 1) Joscha PCA (EU finescale)

## 1b) Add Colors

In [3]:
df = pd.read_csv("./projectPCA/data/joscha_v1/joscha.ho_proj.maf05.tsv", sep="\t")
print(f"Loaded {len(df)} HO Projections onto Joscha PCA")

Loaded 1300 HO Projections onto Joscha PCA

### Filter to relevant pops

In [7]:
ls=["Spanish", "Basque", "French", "Italian_North", "Sicilian", "Sardinian", 
    "Russian", "Finnish", "Ukrainian", "Greek", "Hungarian", 
    "Orcadian", "Norwegian", "Icelandic", "English", "Croatian", "Czech", "Scottish", 
    "Albanian", "Bulgarian"]

cs=["red", "maroon", "yellow", "orange", "deeppink", "brown", "blue", "salmon", 
    "pink", "violet", "magenta", "black", "saddlebrown", 
    "dimgray", "silver", "royalblue", "aqua", "ivory", "plum", "fuchsia"]

In [21]:
def create_subset_colors(df, ls=[], cs=[], savepath="", delete_substrings=[]):
    """Subset PCA dataframe and color_code"""
    dfs_new = []
    
    for l,c in zip (ls, cs):
        dft = df[df["pop"].str.contains(l)].copy()
        print(f"Found {len(dft)} of {l}")
        dft["c"] = c
    
        dfs_new.append(dft)
    df1 = pd.concat(dfs_new).reset_index(drop=True)
    for d in delete_substrings:
        df1["pop"] = df1["pop"].str.replace(d, "")
    if len(savepath)>0:
        df1.to_csv(savepath, sep="\t", index=False)
        print(f"Saved to: {savepath}")
    return df1

In [22]:
### Save
df1 = create_subset_colors(df, ls=ls, cs=cs, savepath="./projectPCA/data/joscha_v1/joscha.ho_proj.euro_c.maf05.tsv",
                          delete_substrings=[".HO", "Ignore_"])

Found 178 of Spanish
Found 32 of Basque
Found 63 of French
Found 21 of Italian_North
Found 11 of Sicilian
Found 27 of Sardinian
Found 72 of Russian
Found 7 of Finnish
Found 13 of Ukrainian
Found 22 of Greek
Found 20 of Hungarian
Found 13 of Orcadian
Found 11 of Norwegian
Found 12 of Icelandic
Found 10 of English
Found 10 of Croatian
Found 10 of Czech
Found 4 of Scottish
Found 6 of Albanian
Found 10 of Bulgarian
Saved to: ./projectPCA/data/joscha_v1/joscha.ho_proj.euro_c.maf05.tsv

In [23]:
df1

          pc1       pc2    #SNP             iid        pop        c
0   -0.006974 -0.006904  112668      HG01500.HO    Spanish      red
1   -0.008879 -0.007012  112671      HG01501.HO    Spanish      red
2   -0.009376 -0.008506  112588      HG01503.HO    Spanish      red
3   -0.011852 -0.010374  112710      HG01504.HO    Spanish      red
4   -0.005734 -0.009228  112723      HG01506.HO    Spanish      red
..        ...       ...     ...             ...        ...      ...
547 -0.006967  0.003133  112694  BulgarianB1.HO  Bulgarian  fuchsia
548 -0.013915  0.002654  112547  BulgarianC1.HO  Bulgarian  fuchsia
549 -0.006982  0.005511  112747  BulgarianF1.HO  Bulgarian  fuchsia
550 -0.006691  0.001447  112733  BulgarianH2.HO  Bulgarian  fuchsia
551 -0.003883  0.001262  112645  BulgarianF2.HO  Bulgarian  fuchsia

[552 rows x 6 columns]

# 2) Human Origin PCA

In [11]:
!cp /mnt/archgen/users/xiaowen/Kamenice/1024/PCA/0925/pca_shrink.txt /mnt/archgen/users/hringbauer/scripts/pca/pca_westeurasia.txt

# 3) Eurasian PCA
Based on Xiaowen's run via `/mnt/archgen/users/xiaowen/Georgia_final/PCA/0225/PCA/pcaGeorgia_Eurasia.txt`

### 3a) Run the PCA
Copy over the parfile, and manually edited it to output SNP weights (18.2.2026)

In [12]:
parfile_path = "/mnt/archgen/users/hringbauer/scripts/pca/pca_eurasia.txt"

In [13]:
!cp /mnt/archgen/users/xiaowen/Georgia_final/PCA/0225/PCA/pcaGeorgia_Eurasia.txt $parfile_path

In [9]:
!cat $parfile_path

genotypename:	/mnt/archgen/users/xiaowen/Kamenice/1024/genotype/masterdataset/KNC_AADR_HO_0925.geno
snpname:	/mnt/archgen/users/xiaowen/Kamenice/1024/genotype/masterdataset/KNC_AADR_HO_0925.snp
indivname:	/mnt/archgen/users/xiaowen/Kamenice/1024/genotype/masterdataset/KNC_AADR_HO_0925.ind
poplistname:	/mnt/archgen/users/xiaowen/Iraq_Syria/0325/PCA/0825/PCA_list.txt
evecoutname:	/mnt/archgen/users/hringbauer/output/pca/2026.02.18/eurasia_AADR_noshrink.evec
evaloutname:	/mnt/archgen/users/hringbauer/output/pca/2026.02.18/eurasia_AADR_noshrink.eval
snpweightoutname:	/mnt/archgen/users/hringbauer/output/pca/2026.02.18/eurasia_AADR_noshrink.weight
lsqproject: YES
shrinkmode: NO
outliermode: 2
numoutevec: 4
numthreads: 8
hiprecision: YES

### Actual Run of smartpca
Use in a terminal:

`module load eigensoft`

In [19]:
!echo smartpca -p $parfile_path

smartpca -p /mnt/archgen/users/hringbauer/scripts/pca/pca_eurasia.txt

The actual run used smartpca 18140. It took about 30 minutes.

## 3b) Preprocess smartpca output for inclusion in projectPCA

In [56]:
df = pd.read_csv("/mnt/archgen/users/hringbauer/output/pca/2026.02.18/eurasia_AADR_noshrink.weight", sep="\s+", header=None)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_842153/515128285.py:1: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv("/mnt/archgen/users/hringbauer/output/pca/2026.02.18/eurasia_AADR_noshrink.weight", sep="\s+", header=None)

In [57]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,rs3094315,1,752566,-0.364441,-0.919171,-0.243039,0.657441,-0.810157,-1.308217,1.289090,-1.381496,1.461435,-0.121835
1,rs7419119,1,842013,0.049318,1.578073,1.460774,0.055508,-0.027585,-0.738186,-0.521551,0.181789,-2.123433,1.498564
2,rs13302957,1,891021,1.339312,-0.997641,-0.787138,-1.400762,-0.643818,0.293882,0.623727,-2.099656,0.467469,-0.633447
3,rs6696609,1,903426,-0.073190,1.065799,1.347071,-0.126116,0.598763,-1.191279,0.446633,1.702348,0.992004,0.827583
4,rs8997,1,949654,-0.281491,0.819780,-1.149785,-0.391570,-0.951423,0.988529,1.308450,-0.594262,-0.628160,0.062543
...,...,...,...,...,...,...,...,...,...,...,...,...,...
514786,rs10451,22,51162059,-0.640676,-0.222074,-0.238336,-1.990610,-2.140036,0.702819,-1.388014,-0.537246,0.047614,2.164229
514787,rs715586,22,51163138,0.327719,0.664787,-0.952067,-1.215440,-1.182034,-0.513969,0.370054,0.133454,0.560357,-0.009752
514788,rs8137951,22,51165664,-0.613648,-0.193874,-0.285011,-1.978163,-2.173794,1.014967,-1.406754,-0.333400,0.091025,1.777399
514789,rs3810648,22,51175626,0.399719,-0.437908,-1.196770,-0.927223,-1.146523,2.143642,0.345807,0.305894,0.387185,-0.459546
514790,rs78827609,22,51176347,-0.133329,-0.254266,-0.113475,-0.009512,0.055137,0.011002,0.277669,-0.189630,0.449546,-0.627923